debug

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -40,7 +40,10 @@ steps:
 
         echo "---------------------------------------------------------"
 
-        _COMPILATION_RESULT_ID=$(jq -r '.name' /workspace/response.json) 
+
+        echo "Where is jq?"
+        which jq || echo "jq NOT FOUND"
+        _COMPILATION_RESULT_ID=$($(which jq) -r '.name' /workspace/response.json) 
 
         echo "------------------------------ COMPILATION_RESULT_ID --------------------------"
         echo "Compilation Result ID: ${_COMPILATION_RESULT_ID}"
